### ISSUE TITLE
Extract human masks

### ISSUE THREAD

**Issue by ghost** [BobbySolo/JTAMods#1]
Can this tool extract human masks?

**Comment by fabbrimatteo** [comment]
Unfortunately no. This mod only extracts body joints coordinates with their relative person id. The game does not provide any API to extract segmentation masks.

In order to do it, you should use a middleware that interacts directly with the GPU, such as [ReederDoc](https://renderdoc.org).

For more information i suggest you to read this paper: [Playing for Benchmarks](http://vladlen.info/papers/playing-for-benchmarks.pdf).
