### ISSUE TITLE
Convert 3D coordinates to 2D

### ISSUE THREAD

**Issue by wematan** [BobbySolo/JTAMods#3]
Is there an easy way to convert x3D y3D z3D to 2D x,y pixels?
The output only contains 3D coordinates.

Thanks.

**Comment by fabbrimatteo** [comment]
Firstly, you have to perform a roto-translation to have the origin in correspondence to the camera view-point:

<img src="https://latex.codecogs.com/gif.latex?\huge&space;\begin{bmatrix}&space;X'\\&space;Y'\\&space;Z'&space;\end{bmatrix}&space;=&space;\left&space;(&space;\begin{bmatrix}&space;X\\&space;Y\\&space;Z&space;\end{bmatrix}&space;-&space;\begin{bmatrix}&space;X_{\mathrm{cam}}\\&space;Y_{\mathrm{cam}}\\&space;Z_{\mathrm{cam}}&space;\end{bmatrix}&space;\right&space;)\cdot&space;\begin{bmatrix}&space;\cos\beta&space;\cos\gamma&space;&&space;-\cos\alpha&space;\sin\gamma&space;&plus;&space;\sin\alpha&space;\sin\beta&space;\cos\gamma&space;&&space;\sin\alpha&space;\sin\gamma&space;&plus;&space;\cos\alpha&space;\sin\beta&space;\cos\gamma&space;\\&space;\cos\beta\sin\gamma&space;&&space;\cos\alpha&space;\cos\gamma&space;&plus;&space;\sin\alpha&space;\sin\beta&space;\sin\gamma&space;&&space;-&space;\sin\alpha&space;\cos\gamma&space;&plus;&space;\cos\alpha&space;\sin\beta&space;\sin\gamma&space;\\&space;-\sin\beta&space;&&space;\sin\alpha&space;\cos\beta&space;&&space;\cos\alpha&space;\cos\beta&space;\\&space;\end{bmatrix}" title="\huge \begin{bmatrix} X'\\ Y'\\ Z' \end{bmatrix} = \left ( \begin{bmatrix} X\\ Y\\ Z \end{bmatrix} - \begin{bmatrix} X_{\mathrm{cam}}\\ Y_{\mathrm{cam}}\\ Z_{\mathrm{cam}} \end{bmatrix} \right )\cdot \begin{bmatrix} \cos\beta \cos\gamma & -\cos\alpha \sin\gamma + \sin\alpha \sin\beta \cos\gamma & \sin\alpha \sin\gamma + \cos\alpha \sin\beta \cos\gamma \\ \cos\beta\sin\gamma & \cos\alpha \cos\gamma + \sin\alpha \sin\beta \sin\gamma & - \sin\alpha \cos\gamma + \cos\alpha \sin\beta \sin\gamma \\ -\sin\beta & \sin\alpha \cos\beta & \cos\alpha \cos\beta \\ \end{bmatrix}" />

Where:
- [*X*, *Y*, *Z*] are the 3D coords that you want to convert
- [*X*cam, *Y*cam, *Z*cam] are the 3D coords of the camera
- [α, β, γ] are the components of the camera rotation

After that, using the field of view parameter (that you can find in the annotation) you have to calculate the field of view: 

<img align="middle" src="https://latex.codecogs.com/gif.latex?f&space;=&space;\frac{H}{2}&space;\cdot&space;\cot\left&space;({\frac{FOV}{2}}&space;\right&space;)" title="f = \frac{H}{2} \cdot \cot\left ({\frac{FOV}{2}} \right )" />

Now, project the transformed 3D coords (*X*', *Y*', *Z*') over the image plane in order to find 2D coords *x* and *y*:

<img src="https://latex.codecogs.com/gif.latex?\small&space;\left\{\begin{matrix}&space;x&space;=&space;&&space;f&space;\cdot&space;\frac{X'}{Y'}&space;&plus;&space;\frac{W}{2}\\&space;y&space;=&space;&&space;\frac{H}{2}&space;-&space;f&space;\cdot&space;\frac{Z'}{Y'}\\&space;\end{matrix}\right." title="\small \left\{\begin{matrix} x = & f \cdot \frac{X'}{Y'} + \frac{W}{2}\\ y = & \frac{H}{2} - f \cdot \frac{Z'}{Y'}\\ \end{matrix}\right." />

Where *W* and *H* are the width and height of the 2D plane (in our case are 1920 and 1080). 

*Note*: all angles are expressed in radiants.

**Comment by wematan** [comment]
Hi Thanks for the info. 

Few other questions regarding the conversion:
1. FOV is in Degrees? and if so do i need to convert it to radians in order to calculate 1/tan(Fov/2)?
2. do i need to convert α, β, γ to radians as well?
Thanks.

**Comment by fabbrimatteo** [comment]
Yes, in our .csv, all the angles are in degrees. So, you have to convert FOV, α, β and γ to radiants.

**Comment by mohammadakz** [comment]
@fabbrimatteo Hi thanks for your explanation, what do you mean about "[α, β, γ] are the components of the camera rotation". Does it mean that the camera is rotated or not? If you could explain, please. thanks in advance

**Comment by fabbrimatteo** [comment]
The camera (and every object in a space) is always rotated to some quantity with respect to the reference system of the world. And you need thos values if you want to change your reference system according to the camera.

**Comment by montmejat** [comment]
Hello, sorry for bringing this back up and thanks for what you have shared. I'm using the method you have talked about here (`_WORLD3D_TO_SCREEN2D` has the same effect) but I'm getting some weird distortion effects around the edges. Do you know if there would be anyway to fix this? Thanks.

![GTA Image Distortion](https://user-images.githubusercontent.com/29719028/148049395-66c0cf44-2040-4485-ae49-44126259b85a.png)

**Comment by fabbrimatteo** [comment]
Try using this mod: https://www.gta5-mods.com/misc/no-chromatic-aberration-lens-distortion-1-41

**Comment by montmejat** [comment]
That perfectly fixed my problem, thanks! 😄

**Comment by mshooter** [comment]
> Firstly, you have to perform a roto-translation to have the origin in correspondence to the camera view-point:
> 
> ![](https://camo.githubusercontent.com/3b4db7473ada27dd5f11cb695a94aec6208cb558f582a2995508aa6277828390/68747470733a2f2f6c617465782e636f6465636f67732e636f6d2f6769662e6c617465783f5c687567652673706163653b5c626567696e7b626d61747269787d2673706163653b58275c5c2673706163653b59275c5c2673706163653b5a272673706163653b5c656e647b626d61747269787d2673706163653b3d2673706163653b5c6c6566742673706163653b282673706163653b5c626567696e7b626d61747269787d2673706163653b585c5c2673706163653b595c5c2673706163653b5a2673706163653b5c656e647b626d61747269787d2673706163653b2d2673706163653b5c626567696e7b626d61747269787d2673706163653b585f7b5c6d617468726d7b63616d7d7d5c5c2673706163653b595f7b5c6d617468726d7b63616d7d7d5c5c2673706163653b5a5f7b5c6d617468726d7b63616d7d7d2673706163653b5c656e647b626d61747269787d2673706163653b5c72696768742673706163653b295c63646f742673706163653b5c626567696e7b626d61747269787d2673706163653b5c636f735c626574612673706163653b5c636f735c67616d6d612673706163653b262673706163653b2d5c636f735c616c7068612673706163653b5c73696e5c67616d6d612673706163653b2b2673706163653b5c73696e5c616c7068612673706163653b5c73696e5c626574612673706163653b5c636f735c67616d6d612673706163653b262673706163653b5c73696e5c616c7068612673706163653b5c73696e5c67616d6d612673706163653b2b2673706163653b5c636f735c616c7068612673706163653b5c73696e5c626574612673706163653b5c636f735c67616d6d612673706163653b5c5c2673706163653b5c636f735c626574615c73696e5c67616d6d612673706163653b262673706163653b5c636f735c616c7068612673706163653b5c636f735c67616d6d612673706163653b2b2673706163653b5c73696e5c616c7068612673706163653b5c73696e5c626574612673706163653b5c73696e5c67616d6d612673706163653b262673706163653b2d2673706163653b5c73696e5c616c7068612673706163653b5c636f735c67616d6d612673706163653b2b2673706163653b5c636f735c616c7068612673706163653b5c73696e5c626574612673706163653b5c73696e5c67616d6d612673706163653b5c5c2673706163653b2d5c73696e5c626574612673706163653b262673706163653b5c73696e5c616c7068612673706163653b5c636f735c626574612673706163653b262673706163653b5c636f735c616c7068612673706163653b5c636f735c626574612673706163653b5c5c2673706163653b5c656e647b626d61747269787d)
> 
> Where:
> 
> * [_X_, _Y_, _Z_] are the 3D coords that you want to convert
> * [_X_cam, _Y_cam, _Z_cam] are the 3D coords of the camera
> * [α, β, γ] are the components of the camera rotation
> 
> After that, using the field of view parameter (that you can find in the annotation) you have to calculate the field of view:
> 
> ![](https://camo.githubusercontent.com/6a8776c47729b65e0c4afbcb12c00f01a38aa1ae01937699867bd359ecaf6bb8/68747470733a2f2f6c617465782e636f6465636f67732e636f6d2f6769662e6c617465783f662673706163653b3d2673706163653b5c667261637b487d7b327d2673706163653b5c63646f742673706163653b5c636f745c6c6566742673706163653b287b5c667261637b464f567d7b327d7d2673706163653b5c72696768742673706163653b29)
> 
> Now, project the transformed 3D coords (_X_', _Y_', _Z_') over the image plane in order to find 2D coords _x_ and _y_:
> 
> ![](https://camo.githubusercontent.com/aef5d6fb1d10a9bcb8e5038f2bdb03f96a68487ad5ba5f2e76662f2f031ad736/68747470733a2f2f6c617465782e636f6465636f67732e636f6d2f6769662e6c617465783f5c736d616c6c2673706163653b5c6c6566745c7b5c626567696e7b6d61747269787d2673706163653b782673706163653b3d2673706163653b262673706163653b662673706163653b5c63646f742673706163653b5c667261637b58277d7b59277d2673706163653b2b2673706163653b5c667261637b577d7b327d5c5c2673706163653b792673706163653b3d2673706163653b262673706163653b5c667261637b487d7b327d2673706163653b2d2673706163653b662673706163653b5c63646f742673706163653b5c667261637b5a277d7b59277d5c5c2673706163653b5c656e647b6d61747269787d5c72696768742e)
> 
> Where _W_ and _H_ are the width and height of the 2D plane (in our case are 1920 and 1080).
> 
> _Note_: all angles are expressed in radiants.

Hi, a quick question. 
In which coordinate system was this? and what is the Up axis?

**Comment by fabbrimatteo** [comment]
I do not have such information anymore. But with the new annotations you can use this formula:
<img align="middle" src="https://latex.codecogs.com/svg.image?\begin{cases}&space;x&space;=&space;f&space;\cdot&space;\frac{X'}{Z'}&space;&plus;&space;\frac{W}{2}\\&space;y&space;=&space;f&space;\cdot&space;\frac{Y'}{Z'}&space;&plus;&space;\frac{H}{2}\\&space;\end{cases}" />

Take a look at the pinhole camera model: https://docs.opencv.org/3.4/d9/d0c/group__calib3d.html

**Comment by mshooter** [comment]
Is the focal length in mm or in pixels?

**Comment by fabbrimatteo** [comment]
The focal length is in pixels.
