### ISSUE TITLE
Thoughts on adding joints to DatasetAnnotator?

### ISSUE THREAD

**Issue by Godatplay** [BobbySolo/JTAMods#4]
Is there any reason not to add more joints to the annotator? Synthetic data seems like a perfect opportunity to provide data for feet especially, and even palms and fingers, since those are more difficult to track IRL without hardware that dirties captured pixels. In fact, including at least `SKEL_L_Toe0` and `SKEL_R_Toe0` would make a great complement to the new [human foot keypoint dataset (HFKD?)](https://cmu-perceptual-computing-lab.github.io/foot_keypoint_dataset/).

One of the best 3D datasets Human 3.6M (one of a couple datasets oddly missing from the list in your paper) has 32 joints, so this would complement that as well.

**Comment by fabbrimatteo** [comment]
There is absolutely no reason not to add more joints to the mod.

We have just added the joints useful for our purposes, in order to not slow down the computation.

Here you can find all the available joints on GTA: https://pastebin.com/D7JMnX1g

You can easily modify the source code of the DatasetAnnotator mod in order to add the new joints:
- update the map in the `JTA-Mods/DatasetAnnotator/dictionary.h` by adding the new bones
- update `JTA-Mods/DatasetAnnotator/scenario.cpp` on lines 154-174, adding the new bones accordingly

Note that some joints seem to be bugged.

**Comment by Godatplay** [comment]
Thanks so much! That's great news, and thanks for the shortcut resources.

**Comment by Yuliang-Zou** [comment]
@Godatplay , have you successfully added those foot keypoints?
